# set_property mark_debug true [get_nets [list {IALU_IN1[27]} {IALU_IN1[26]} {IALU_IN1[25]} {IALU_IN1[24]} {IALU_IN1[23]} {IALU_IN1[22]} {IALU_IN1[31]} {IALU_IN1[30]} {IALU_IN1[29]} {IALU_IN1[28]} {IALU_IN1[15]} {IALU_IN1[21]} {IALU_IN1[6]} {IALU_IN1[4]} {IALU_IN1[20]} {IALU_IN1[19]} {IALU_IN1[10]} {IALU_IN1[3]} {IALU_IN1[18]} {IALU_IN1[17]} {IALU_IN1[16]} {IALU_IN1[5]} {IALU_IN1[2]} {IALU_IN1[7]} {IALU_IN1[9]} {IALU_IN1[8]} {IALU_IN1[14]} {IALU_IN1[1]} {IALU_IN1[13]} ialu_inst_i_32_n_0 {IALU_IN1[11]} {IALU_IN1[12]}]]
# set_property mark_debug true [get_nets [list {IALU_IN2[3]} {IALU_IN2[2]} {IALU_IN2[23]} {IALU_IN2[14]} {IALU_IN2[20]} {IALU_IN2[4]} {IALU_IN2[15]} {IALU_IN2[5]} {IALU_IN2[6]} {IALU_IN2[7]} {IALU_IN2[21]} {IALU_IN2[13]} {IALU_IN2[8]} {IALU_IN2[9]} {IALU_IN2[19]} {IALU_IN2[22]} {IALU_IN2[16]} {IALU_IN2[17]} {IALU_IN2[10]} {IALU_IN2[11]} {IALU_IN2[12]} {IALU_IN2[18]} {IALU_IN2[0]} {IALU_IN2[1]} {IALU_IN2[28]} {IALU_IN2[29]} {IALU_IN2[30]} {IALU_IN2[31]} {IALU_IN2[24]} {IALU_IN2[25]} {IALU_IN2[26]} {IALU_IN2[27]}]]
# set_property mark_debug true [get_nets [list {aluop[0]} {aluop[1]} {aluop[2]} {aluop[3]} {aluop[4]}]]
# set_property mark_debug true [get_nets [list {instruction[4]} {instruction[7]} {instruction[0]} {instruction[1]} {instruction[2]} {instruction[3]} {instruction[11]} {instruction[20]} {instruction[26]} {instruction[13]} {instruction[25]} {instruction[5]} {instruction[30]} {instruction[12]} {instruction[21]} {instruction[6]} {instruction[22]} {instruction[14]} {instruction[28]} {instruction[23]} {instruction[17]} {instruction[8]} {instruction[9]} {instruction[29]} {instruction[15]} {instruction[27]} {instruction[24]} {instruction[10]} {instruction[16]} {instruction[19]} {instruction[31]} {instruction[18]}]]
# set_property mark_debug true [get_nets [list {ialu_OUT[1]} {ialu_OUT[0]} {ialu_OUT[15]} {ialu_OUT[16]} {ialu_OUT[2]} {ialu_OUT[3]} {ialu_OUT[13]} {ialu_OUT[20]} {ialu_OUT[12]} {ialu_OUT[4]} {ialu_OUT[23]} {ialu_OUT[30]} {ialu_OUT[17]} {ialu_OUT[5]} {ialu_OUT[14]} {ialu_OUT[22]} {ialu_OUT[24]} {ialu_OUT[25]} {ialu_OUT[27]} {ialu_OUT[11]} {ialu_OUT[6]} {ialu_OUT[7]} {ialu_OUT[8]} {ialu_OUT[9]} {ialu_OUT[26]} {ialu_OUT[21]} {ialu_OUT[28]} {ialu_OUT[18]} {ialu_OUT[19]} {ialu_OUT[31]} {ialu_OUT[10]} {ialu_OUT[29]}]]
# set_property mark_debug true [get_nets [list regs_inst_i_32_n_0 {WriteBack_data[25]} {WriteBack_data[27]} {WriteBack_data[31]} {WriteBack_data[30]} {WriteBack_data[29]} {WriteBack_data[28]} {WriteBack_data[26]} {WriteBack_data[24]} {WriteBack_data[23]} {WriteBack_data[11]} {WriteBack_data[7]} {WriteBack_data[15]} {WriteBack_data[20]} {WriteBack_data[17]} {WriteBack_data[12]} {WriteBack_data[6]} {WriteBack_data[19]} {WriteBack_data[22]} {WriteBack_data[2]} {WriteBack_data[10]} {WriteBack_data[4]} {WriteBack_data[3]} {WriteBack_data[21]} {WriteBack_data[13]} {WriteBack_data[9]} {WriteBack_data[5]} {WriteBack_data[8]} {WriteBack_data[1]} {WriteBack_data[18]} {WriteBack_data[16]} {WriteBack_data[14]}]]
# set_property mark_debug true [get_nets [list {d1[14]} {d1[10]} {d1[4]} {d1[5]} {d1[31]} {d1[19]} {d1[15]} {d1[16]} {d1[26]} {d1[30]} {d1[17]} {d1[21]} {d1[6]} {d1[7]} {d1[8]} {d1[9]} {d1[22]} {d1[24]} {d1[29]} {d1[11]} {d1[23]} {d1[28]} {d1[27]} {d1[18]} {d1[20]} {d1[12]} {d1[13]} {d1[25]} {d1[0]} {d1[1]} {d1[2]} {d1[3]}]]
# set_property mark_debug true [get_nets [list {d2[2]} {d2[0]} {d2[13]} {d2[23]} {d2[1]} {d2[18]} {d2[29]} {d2[17]} {d2[19]} {d2[3]} {d2[4]} {d2[5]} {d2[12]} {d2[24]} {d2[14]} {d2[6]} {d2[28]} {d2[20]} {d2[30]} {d2[27]} {d2[31]} {d2[21]} {d2[7]} {d2[16]} {d2[22]} {d2[11]} {d2[8]} {d2[9]} {d2[10]} {d2[26]} {d2[25]} {d2[15]}]]
# set_property mark_debug true [get_nets [list {branch_type[0]} {branch_type[1]} {branch_type[2]}]]
# set_property mark_debug true [get_nets [list jump]]
# set_property mark_debug true [get_nets [list {program_counter[10]} {program_counter[3]} {program_counter[4]} {program_counter[5]} {program_counter[6]} {program_counter[28]} {program_counter[19]} {program_counter[7]} {program_counter[20]} {program_counter[29]} {program_counter[31]} {program_counter[22]} {program_counter[26]} {program_counter[8]} {program_counter[9]} {program_counter[27]} {program_counter[17]} {program_counter[21]} {program_counter[11]} {program_counter[18]} {program_counter[30]} {program_counter[16]} {program_counter[12]} {program_counter[23]} {program_counter[24]} {program_counter[15]} {program_counter[14]} {program_counter[13]} {program_counter[25]} {program_counter[1]} {program_counter[2]}]]
# set_property mark_debug true [get_nets [list instruction_rom_i_1_n_0]]
# set_property mark_debug true [get_nets [list serial_i_IBUF]]
# set_property mark_debug true [get_nets [list programming_mode_OBUF]]
# set_property mark_debug true [get_nets [list mwe]]
# set_property mark_debug true [get_nets [list we]]
# set_property mark_debug true [get_nets [list AUIPC_sig]]
# set_property mark_debug true [get_nets [list {dtype[0]} {dtype[1]} {dtype[2]}]]
# set_property mark_debug true [get_nets [list load]]
# set_property mark_debug true [get_nets [list {Type[0]} {Type[1]} {Type[2]}]]
# set_property mark_debug true [get_nets [list {lsu_d_out[0]} {lsu_d_out[1]} {lsu_d_out[3]} {lsu_d_out[2]} {lsu_d_out[4]} {lsu_d_out[14]} {lsu_d_out[12]} {lsu_d_out[13]} {lsu_d_out[5]} {lsu_d_out[6]} {lsu_d_out[18]} {lsu_d_out[7]} {lsu_d_out[8]} {lsu_d_out[19]} {lsu_d_out[15]} {lsu_d_out[16]} {lsu_d_out[17]} {lsu_d_out[9]} {lsu_d_out[10]} {lsu_d_out[11]} {lsu_d_out[20]} {lsu_d_out[21]} {lsu_d_out[22]} {lsu_d_out[30]} {lsu_d_out[31]} {lsu_d_out[23]} {lsu_d_out[24]} {lsu_d_out[25]} {lsu_d_out[29]} {lsu_d_out[26]} {lsu_d_out[27]} {lsu_d_out[28]}]]
# set_property mark_debug true [get_nets [list {gpioA_out_OBUF[25]} {gpioA_out_OBUF[22]} {gpioA_out_OBUF[23]} {gpioA_out_OBUF[24]} {gpioA_out_OBUF[26]} {gpioA_out_OBUF[27]} {gpioA_out_OBUF[28]} {gpioA_out_OBUF[31]} {gpioA_out_OBUF[29]} {gpioA_out_OBUF[30]} {gpioA_out_OBUF[0]} {gpioA_out_OBUF[1]} {gpioA_out_OBUF[2]} {gpioA_out_OBUF[3]} {gpioA_out_OBUF[4]} {gpioA_out_OBUF[5]} {gpioA_out_OBUF[13]} {gpioA_out_OBUF[19]} {gpioA_out_OBUF[6]} {gpioA_out_OBUF[7]} {gpioA_out_OBUF[20]} {gpioA_out_OBUF[8]} {gpioA_out_OBUF[12]} {gpioA_out_OBUF[9]} {gpioA_out_OBUF[18]} {gpioA_out_OBUF[14]} {gpioA_out_OBUF[10]} {gpioA_out_OBUF[15]} {gpioA_out_OBUF[21]} {gpioA_out_OBUF[11]} {gpioA_out_OBUF[16]} {gpioA_out_OBUF[17]}]]
# set_property mark_debug true [get_nets [list {gpioB_out_OBUF[7]} {gpioB_out_OBUF[1]} {gpioB_out_OBUF[2]} {gpioB_out_OBUF[28]} {gpioB_out_OBUF[22]} {gpioB_out_OBUF[25]} {gpioB_out_OBUF[3]} {gpioB_out_OBUF[24]} {gpioB_out_OBUF[31]} {gpioB_out_OBUF[23]} {gpioB_out_OBUF[4]} {gpioB_out_OBUF[17]} {gpioB_out_OBUF[12]} {gpioB_out_OBUF[16]} {gpioB_out_OBUF[18]} {gpioB_out_OBUF[29]} {gpioB_out_OBUF[30]} {gpioB_out_OBUF[5]} {gpioB_out_OBUF[6]} {gpioB_out_OBUF[27]} {gpioB_out_OBUF[8]} {gpioB_out_OBUF[9]} {gpioB_out_OBUF[14]} {gpioB_out_OBUF[10]} {gpioB_out_OBUF[20]} {gpioB_out_OBUF[11]} {gpioB_out_OBUF[13]} {gpioB_out_OBUF[19]} {gpioB_out_OBUF[26]} {gpioB_out_OBUF[15]} {gpioB_out_OBUF[21]} {gpioB_out_OBUF[0]}]]
# set_property mark_debug true [get_nets [list {lsu_inst/ram_ip/bank_addr[0][9]} {lsu_inst/ram_ip/bank_addr[0][8]} {lsu_inst/ram_ip/bank_addr[0][7]}]]
# set_property mark_debug true [get_nets [list {lsu_inst/ram_ip/bank_addr[1][9]} {lsu_inst/ram_ip/bank_addr[1][8]} {lsu_inst/ram_ip/bank_addr[1][7]} {lsu_inst/ram_ip/bank_addr[1][6]}]]
# set_property mark_debug true [get_nets [list {lsu_inst/ram_ip/bank_addr[2][9]} {lsu_inst/ram_ip/bank_addr[2][7]} {lsu_inst/ram_ip/bank_addr[2][8]}]]
# set_property mark_debug true [get_nets [list {lsu_inst/ram_ip/addr_i[0]} {lsu_inst/ram_ip/addr_i[1]} {lsu_inst/ram_ip/addr_i[2]} {lsu_inst/ram_ip/addr_i[8]} {lsu_inst/ram_ip/addr_i[10]} {lsu_inst/ram_ip/addr_i[11]} {lsu_inst/ram_ip/addr_i[3]} {lsu_inst/ram_ip/addr_i[4]} {lsu_inst/ram_ip/addr_i[5]} {lsu_inst/ram_ip/addr_i[6]} {lsu_inst/ram_ip/addr_i[7]} {lsu_inst/ram_ip/addr_i[9]}]]
# create_debug_core u_ila_0 ila
# set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
# set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
# set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
# set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
# set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
# set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
# set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
# set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
# startgroup 
# set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0 ]
# set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0 ]
# set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0 ]
# set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0 ]
# endgroup
# connect_debug_port u_ila_0/clk [get_nets [list clk_i_IBUF_BUFG ]]
# set_property port_width 3 [get_debug_ports u_ila_0/probe0]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
# connect_debug_port u_ila_0/probe0 [get_nets [list {branch_type[0]} {branch_type[1]} {branch_type[2]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 31 [get_debug_ports u_ila_0/probe1]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
# connect_debug_port u_ila_0/probe1 [get_nets [list {WriteBack_data[1]} {WriteBack_data[2]} {WriteBack_data[3]} {WriteBack_data[4]} {WriteBack_data[5]} {WriteBack_data[6]} {WriteBack_data[7]} {WriteBack_data[8]} {WriteBack_data[9]} {WriteBack_data[10]} {WriteBack_data[11]} {WriteBack_data[12]} {WriteBack_data[13]} {WriteBack_data[14]} {WriteBack_data[15]} {WriteBack_data[16]} {WriteBack_data[17]} {WriteBack_data[18]} {WriteBack_data[19]} {WriteBack_data[20]} {WriteBack_data[21]} {WriteBack_data[22]} {WriteBack_data[23]} {WriteBack_data[24]} {WriteBack_data[25]} {WriteBack_data[26]} {WriteBack_data[27]} {WriteBack_data[28]} {WriteBack_data[29]} {WriteBack_data[30]} {WriteBack_data[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 5 [get_debug_ports u_ila_0/probe2]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
# connect_debug_port u_ila_0/probe2 [get_nets [list {aluop[0]} {aluop[1]} {aluop[2]} {aluop[3]} {aluop[4]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 3 [get_debug_ports u_ila_0/probe3]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
# connect_debug_port u_ila_0/probe3 [get_nets [list {dtype[0]} {dtype[1]} {dtype[2]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe4]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
# connect_debug_port u_ila_0/probe4 [get_nets [list {d2[0]} {d2[1]} {d2[2]} {d2[3]} {d2[4]} {d2[5]} {d2[6]} {d2[7]} {d2[8]} {d2[9]} {d2[10]} {d2[11]} {d2[12]} {d2[13]} {d2[14]} {d2[15]} {d2[16]} {d2[17]} {d2[18]} {d2[19]} {d2[20]} {d2[21]} {d2[22]} {d2[23]} {d2[24]} {d2[25]} {d2[26]} {d2[27]} {d2[28]} {d2[29]} {d2[30]} {d2[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 12 [get_debug_ports u_ila_0/probe5]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
# connect_debug_port u_ila_0/probe5 [get_nets [list {lsu_inst/ram_ip/addr_i[0]} {lsu_inst/ram_ip/addr_i[1]} {lsu_inst/ram_ip/addr_i[2]} {lsu_inst/ram_ip/addr_i[3]} {lsu_inst/ram_ip/addr_i[4]} {lsu_inst/ram_ip/addr_i[5]} {lsu_inst/ram_ip/addr_i[6]} {lsu_inst/ram_ip/addr_i[7]} {lsu_inst/ram_ip/addr_i[8]} {lsu_inst/ram_ip/addr_i[9]} {lsu_inst/ram_ip/addr_i[10]} {lsu_inst/ram_ip/addr_i[11]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 31 [get_debug_ports u_ila_0/probe6]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
# connect_debug_port u_ila_0/probe6 [get_nets [list {IALU_IN1[1]} {IALU_IN1[2]} {IALU_IN1[3]} {IALU_IN1[4]} {IALU_IN1[5]} {IALU_IN1[6]} {IALU_IN1[7]} {IALU_IN1[8]} {IALU_IN1[9]} {IALU_IN1[10]} {IALU_IN1[11]} {IALU_IN1[12]} {IALU_IN1[13]} {IALU_IN1[14]} {IALU_IN1[15]} {IALU_IN1[16]} {IALU_IN1[17]} {IALU_IN1[18]} {IALU_IN1[19]} {IALU_IN1[20]} {IALU_IN1[21]} {IALU_IN1[22]} {IALU_IN1[23]} {IALU_IN1[24]} {IALU_IN1[25]} {IALU_IN1[26]} {IALU_IN1[27]} {IALU_IN1[28]} {IALU_IN1[29]} {IALU_IN1[30]} {IALU_IN1[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe7]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
# connect_debug_port u_ila_0/probe7 [get_nets [list {IALU_IN2[0]} {IALU_IN2[1]} {IALU_IN2[2]} {IALU_IN2[3]} {IALU_IN2[4]} {IALU_IN2[5]} {IALU_IN2[6]} {IALU_IN2[7]} {IALU_IN2[8]} {IALU_IN2[9]} {IALU_IN2[10]} {IALU_IN2[11]} {IALU_IN2[12]} {IALU_IN2[13]} {IALU_IN2[14]} {IALU_IN2[15]} {IALU_IN2[16]} {IALU_IN2[17]} {IALU_IN2[18]} {IALU_IN2[19]} {IALU_IN2[20]} {IALU_IN2[21]} {IALU_IN2[22]} {IALU_IN2[23]} {IALU_IN2[24]} {IALU_IN2[25]} {IALU_IN2[26]} {IALU_IN2[27]} {IALU_IN2[28]} {IALU_IN2[29]} {IALU_IN2[30]} {IALU_IN2[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 4 [get_debug_ports u_ila_0/probe8]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
# connect_debug_port u_ila_0/probe8 [get_nets [list {lsu_inst/ram_ip/bank_addr[1][6]} {lsu_inst/ram_ip/bank_addr[1][7]} {lsu_inst/ram_ip/bank_addr[1][8]} {lsu_inst/ram_ip/bank_addr[1][9]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 3 [get_debug_ports u_ila_0/probe9]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
# connect_debug_port u_ila_0/probe9 [get_nets [list {Type[0]} {Type[1]} {Type[2]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe10]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
# connect_debug_port u_ila_0/probe10 [get_nets [list {gpioA_out_OBUF[0]} {gpioA_out_OBUF[1]} {gpioA_out_OBUF[2]} {gpioA_out_OBUF[3]} {gpioA_out_OBUF[4]} {gpioA_out_OBUF[5]} {gpioA_out_OBUF[6]} {gpioA_out_OBUF[7]} {gpioA_out_OBUF[8]} {gpioA_out_OBUF[9]} {gpioA_out_OBUF[10]} {gpioA_out_OBUF[11]} {gpioA_out_OBUF[12]} {gpioA_out_OBUF[13]} {gpioA_out_OBUF[14]} {gpioA_out_OBUF[15]} {gpioA_out_OBUF[16]} {gpioA_out_OBUF[17]} {gpioA_out_OBUF[18]} {gpioA_out_OBUF[19]} {gpioA_out_OBUF[20]} {gpioA_out_OBUF[21]} {gpioA_out_OBUF[22]} {gpioA_out_OBUF[23]} {gpioA_out_OBUF[24]} {gpioA_out_OBUF[25]} {gpioA_out_OBUF[26]} {gpioA_out_OBUF[27]} {gpioA_out_OBUF[28]} {gpioA_out_OBUF[29]} {gpioA_out_OBUF[30]} {gpioA_out_OBUF[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe11]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
# connect_debug_port u_ila_0/probe11 [get_nets [list {d1[0]} {d1[1]} {d1[2]} {d1[3]} {d1[4]} {d1[5]} {d1[6]} {d1[7]} {d1[8]} {d1[9]} {d1[10]} {d1[11]} {d1[12]} {d1[13]} {d1[14]} {d1[15]} {d1[16]} {d1[17]} {d1[18]} {d1[19]} {d1[20]} {d1[21]} {d1[22]} {d1[23]} {d1[24]} {d1[25]} {d1[26]} {d1[27]} {d1[28]} {d1[29]} {d1[30]} {d1[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe12]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
# connect_debug_port u_ila_0/probe12 [get_nets [list {instruction[0]} {instruction[1]} {instruction[2]} {instruction[3]} {instruction[4]} {instruction[5]} {instruction[6]} {instruction[7]} {instruction[8]} {instruction[9]} {instruction[10]} {instruction[11]} {instruction[12]} {instruction[13]} {instruction[14]} {instruction[15]} {instruction[16]} {instruction[17]} {instruction[18]} {instruction[19]} {instruction[20]} {instruction[21]} {instruction[22]} {instruction[23]} {instruction[24]} {instruction[25]} {instruction[26]} {instruction[27]} {instruction[28]} {instruction[29]} {instruction[30]} {instruction[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 31 [get_debug_ports u_ila_0/probe13]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
# connect_debug_port u_ila_0/probe13 [get_nets [list {program_counter[1]} {program_counter[2]} {program_counter[3]} {program_counter[4]} {program_counter[5]} {program_counter[6]} {program_counter[7]} {program_counter[8]} {program_counter[9]} {program_counter[10]} {program_counter[11]} {program_counter[12]} {program_counter[13]} {program_counter[14]} {program_counter[15]} {program_counter[16]} {program_counter[17]} {program_counter[18]} {program_counter[19]} {program_counter[20]} {program_counter[21]} {program_counter[22]} {program_counter[23]} {program_counter[24]} {program_counter[25]} {program_counter[26]} {program_counter[27]} {program_counter[28]} {program_counter[29]} {program_counter[30]} {program_counter[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe14]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
# connect_debug_port u_ila_0/probe14 [get_nets [list {gpioB_out_OBUF[0]} {gpioB_out_OBUF[1]} {gpioB_out_OBUF[2]} {gpioB_out_OBUF[3]} {gpioB_out_OBUF[4]} {gpioB_out_OBUF[5]} {gpioB_out_OBUF[6]} {gpioB_out_OBUF[7]} {gpioB_out_OBUF[8]} {gpioB_out_OBUF[9]} {gpioB_out_OBUF[10]} {gpioB_out_OBUF[11]} {gpioB_out_OBUF[12]} {gpioB_out_OBUF[13]} {gpioB_out_OBUF[14]} {gpioB_out_OBUF[15]} {gpioB_out_OBUF[16]} {gpioB_out_OBUF[17]} {gpioB_out_OBUF[18]} {gpioB_out_OBUF[19]} {gpioB_out_OBUF[20]} {gpioB_out_OBUF[21]} {gpioB_out_OBUF[22]} {gpioB_out_OBUF[23]} {gpioB_out_OBUF[24]} {gpioB_out_OBUF[25]} {gpioB_out_OBUF[26]} {gpioB_out_OBUF[27]} {gpioB_out_OBUF[28]} {gpioB_out_OBUF[29]} {gpioB_out_OBUF[30]} {gpioB_out_OBUF[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 3 [get_debug_ports u_ila_0/probe15]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
# connect_debug_port u_ila_0/probe15 [get_nets [list {lsu_inst/ram_ip/bank_addr[0][7]} {lsu_inst/ram_ip/bank_addr[0][8]} {lsu_inst/ram_ip/bank_addr[0][9]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 3 [get_debug_ports u_ila_0/probe16]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
# connect_debug_port u_ila_0/probe16 [get_nets [list {lsu_inst/ram_ip/bank_addr[2][7]} {lsu_inst/ram_ip/bank_addr[2][8]} {lsu_inst/ram_ip/bank_addr[2][9]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe17]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
# connect_debug_port u_ila_0/probe17 [get_nets [list {ialu_OUT[0]} {ialu_OUT[1]} {ialu_OUT[2]} {ialu_OUT[3]} {ialu_OUT[4]} {ialu_OUT[5]} {ialu_OUT[6]} {ialu_OUT[7]} {ialu_OUT[8]} {ialu_OUT[9]} {ialu_OUT[10]} {ialu_OUT[11]} {ialu_OUT[12]} {ialu_OUT[13]} {ialu_OUT[14]} {ialu_OUT[15]} {ialu_OUT[16]} {ialu_OUT[17]} {ialu_OUT[18]} {ialu_OUT[19]} {ialu_OUT[20]} {ialu_OUT[21]} {ialu_OUT[22]} {ialu_OUT[23]} {ialu_OUT[24]} {ialu_OUT[25]} {ialu_OUT[26]} {ialu_OUT[27]} {ialu_OUT[28]} {ialu_OUT[29]} {ialu_OUT[30]} {ialu_OUT[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 32 [get_debug_ports u_ila_0/probe18]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
# connect_debug_port u_ila_0/probe18 [get_nets [list {lsu_d_out[0]} {lsu_d_out[1]} {lsu_d_out[2]} {lsu_d_out[3]} {lsu_d_out[4]} {lsu_d_out[5]} {lsu_d_out[6]} {lsu_d_out[7]} {lsu_d_out[8]} {lsu_d_out[9]} {lsu_d_out[10]} {lsu_d_out[11]} {lsu_d_out[12]} {lsu_d_out[13]} {lsu_d_out[14]} {lsu_d_out[15]} {lsu_d_out[16]} {lsu_d_out[17]} {lsu_d_out[18]} {lsu_d_out[19]} {lsu_d_out[20]} {lsu_d_out[21]} {lsu_d_out[22]} {lsu_d_out[23]} {lsu_d_out[24]} {lsu_d_out[25]} {lsu_d_out[26]} {lsu_d_out[27]} {lsu_d_out[28]} {lsu_d_out[29]} {lsu_d_out[30]} {lsu_d_out[31]} ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe19]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
# connect_debug_port u_ila_0/probe19 [get_nets [list AUIPC_sig ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe20]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
# connect_debug_port u_ila_0/probe20 [get_nets [list ialu_inst_i_32_n_0 ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe21]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
# connect_debug_port u_ila_0/probe21 [get_nets [list instruction_rom_i_1_n_0 ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe22]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
# connect_debug_port u_ila_0/probe22 [get_nets [list jump ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe23]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
# connect_debug_port u_ila_0/probe23 [get_nets [list load ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe24]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
# connect_debug_port u_ila_0/probe24 [get_nets [list mwe ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe25]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
# connect_debug_port u_ila_0/probe25 [get_nets [list programming_mode_OBUF ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe26]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
# connect_debug_port u_ila_0/probe26 [get_nets [list regs_inst_i_32_n_0 ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe27]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
# connect_debug_port u_ila_0/probe27 [get_nets [list serial_i_IBUF ]]
# create_debug_port u_ila_0 probe
# set_property port_width 1 [get_debug_ports u_ila_0/probe28]
# set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
# connect_debug_port u_ila_0/probe28 [get_nets [list we ]]

# file mkdir $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new
# close [ open $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new/riscy_debug.xdc w ]
# add_files -fileset constrs_1 $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new/riscy_debug.xdc
# set_property target_constrs_file $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new/riscy_debug.xdc [current_fileset -constrset]
# save_constraints -force


set_property MARK_DEBUG true [get_nets {program_counter[24]}]
set_property MARK_DEBUG true [get_nets {program_counter[3]}]
set_property MARK_DEBUG true [get_nets {program_counter[1]}]
set_property MARK_DEBUG true [get_nets {program_counter[2]}]
set_property MARK_DEBUG true [get_nets {program_counter[27]}]
set_property MARK_DEBUG true [get_nets {program_counter[29]}]
set_property MARK_DEBUG true [get_nets {program_counter[30]}]
set_property MARK_DEBUG true [get_nets {program_counter[4]}]
set_property MARK_DEBUG true [get_nets {program_counter[19]}]
set_property MARK_DEBUG true [get_nets {program_counter[28]}]
set_property MARK_DEBUG true [get_nets {program_counter[25]}]
set_property MARK_DEBUG true [get_nets {program_counter[22]}]
set_property MARK_DEBUG true [get_nets {program_counter[20]}]
set_property MARK_DEBUG true [get_nets {program_counter[21]}]
set_property MARK_DEBUG true [get_nets {program_counter[14]}]
set_property MARK_DEBUG true [get_nets {program_counter[5]}]
set_property MARK_DEBUG true [get_nets {program_counter[6]}]
set_property MARK_DEBUG true [get_nets {program_counter[7]}]
set_property MARK_DEBUG true [get_nets {program_counter[8]}]
set_property MARK_DEBUG true [get_nets {program_counter[16]}]
set_property MARK_DEBUG true [get_nets {program_counter[17]}]
set_property MARK_DEBUG true [get_nets {program_counter[23]}]
set_property MARK_DEBUG true [get_nets {program_counter[9]}]
set_property MARK_DEBUG true [get_nets {program_counter[10]}]
set_property MARK_DEBUG true [get_nets {program_counter[13]}]
set_property MARK_DEBUG true [get_nets {program_counter[15]}]
set_property MARK_DEBUG true [get_nets {program_counter[31]}]
set_property MARK_DEBUG true [get_nets {program_counter[11]}]
set_property MARK_DEBUG true [get_nets {program_counter[12]}]
set_property MARK_DEBUG true [get_nets {program_counter[26]}]
set_property MARK_DEBUG true [get_nets {program_counter[18]}]
set_property MARK_DEBUG true [get_nets instruction_rom_i_1_n_0]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[0]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[1]}]
set_property MARK_DEBUG true [get_nets instruction_rom/prog_i]
set_property MARK_DEBUG true [get_nets instruction_rom/serial_i]
set_property MARK_DEBUG true [get_nets instruction_rom/data_valid]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[2]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[3]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[4]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[5]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[6]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/byte_recieved[7]}]
set_property MARK_DEBUG true [get_nets {instruction[0]}]
set_property MARK_DEBUG true [get_nets {instruction[10]}]
set_property MARK_DEBUG true [get_nets {instruction[11]}]
set_property MARK_DEBUG true [get_nets {instruction[12]}]
set_property MARK_DEBUG true [get_nets {instruction[24]}]
set_property MARK_DEBUG true [get_nets {instruction[26]}]
set_property MARK_DEBUG true [get_nets {instruction[13]}]
set_property MARK_DEBUG true [get_nets {instruction[22]}]
set_property MARK_DEBUG true [get_nets {instruction[27]}]
set_property MARK_DEBUG true [get_nets {instruction[29]}]
set_property MARK_DEBUG true [get_nets {instruction[31]}]
set_property MARK_DEBUG true [get_nets {instruction[28]}]
set_property MARK_DEBUG true [get_nets {instruction[30]}]
set_property MARK_DEBUG true [get_nets {instruction[14]}]
set_property MARK_DEBUG true [get_nets {instruction[15]}]
set_property MARK_DEBUG true [get_nets {instruction[16]}]
set_property MARK_DEBUG true [get_nets {instruction[19]}]
set_property MARK_DEBUG true [get_nets {instruction[23]}]
set_property MARK_DEBUG true [get_nets {instruction[17]}]
set_property MARK_DEBUG true [get_nets {instruction[18]}]
set_property MARK_DEBUG true [get_nets {instruction[21]}]
set_property MARK_DEBUG true [get_nets {instruction[25]}]
set_property MARK_DEBUG true [get_nets {instruction[20]}]
set_property MARK_DEBUG true [get_nets {instruction[1]}]
set_property MARK_DEBUG true [get_nets {instruction[2]}]
set_property MARK_DEBUG true [get_nets {instruction[3]}]
set_property MARK_DEBUG true [get_nets {instruction[4]}]
set_property MARK_DEBUG true [get_nets {instruction[5]}]
set_property MARK_DEBUG true [get_nets {instruction[6]}]
set_property MARK_DEBUG true [get_nets {instruction[7]}]
set_property MARK_DEBUG true [get_nets {instruction[8]}]
set_property MARK_DEBUG true [get_nets {instruction[9]}]

set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[0]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[1]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[2]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[3]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[4]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[5]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[6]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[7]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[8]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_address[9]}]

set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[0]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[1]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[2]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[3]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[4]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[5]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[6]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[7]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[8]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[9]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[10]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[11]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[12]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[13]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[14]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[15]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[16]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[17]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[18]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[19]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[20]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[21]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[22]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[23]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[24]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[25]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[26]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[27]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[28]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[29]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[30]}]
set_property MARK_DEBUG true [get_nets {instruction_rom/internal_write_data[31]}]

set_property MARK_DEBUG true [get_nets {instruction_rom/internal_we}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_i_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {instruction[0]} {instruction[1]} {instruction[2]} {instruction[3]} {instruction[4]} {instruction[5]} {instruction[6]} {instruction[7]} {instruction[8]} {instruction[9]} {instruction[10]} {instruction[11]} {instruction[12]} {instruction[13]} {instruction[14]} {instruction[15]} {instruction[16]} {instruction[17]} {instruction[18]} {instruction[19]} {instruction[20]} {instruction[21]} {instruction[22]} {instruction[23]} {instruction[24]} {instruction[25]} {instruction[26]} {instruction[27]} {instruction[28]} {instruction[29]} {instruction[30]} {instruction[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 31 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {program_counter[1]} {program_counter[2]} {program_counter[3]} {program_counter[4]} {program_counter[5]} {program_counter[6]} {program_counter[7]} {program_counter[8]} {program_counter[9]} {program_counter[10]} {program_counter[11]} {program_counter[12]} {program_counter[13]} {program_counter[14]} {program_counter[15]} {program_counter[16]} {program_counter[17]} {program_counter[18]} {program_counter[19]} {program_counter[20]} {program_counter[21]} {program_counter[22]} {program_counter[23]} {program_counter[24]} {program_counter[25]} {program_counter[26]} {program_counter[27]} {program_counter[28]} {program_counter[29]} {program_counter[30]} {program_counter[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {instruction_rom/byte_recieved[0]} {instruction_rom/byte_recieved[1]} {instruction_rom/byte_recieved[2]} {instruction_rom/byte_recieved[3]} {instruction_rom/byte_recieved[4]} {instruction_rom/byte_recieved[5]} {instruction_rom/byte_recieved[6]} {instruction_rom/byte_recieved[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list instruction_rom/data_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list instruction_rom_i_1_n_0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list instruction_rom/prog_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list instruction_rom/serial_i]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_i_IBUF_BUFG]

file mkdir $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new
close [ open $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new/riscy_debug.xdc w ]
add_files -fileset constrs_1 $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new/riscy_debug.xdc
set_property target_constrs_file $OUT_DIR/$PROJECT_NAME.srcs/constrs_1/new/riscy_debug.xdc [current_fileset -constrset]
save_constraints -force