read_verilog [ glob ./src/top/params/**]
read_verilog [ glob ./src/top/rtl/top.sv ]
read_verilog [ glob ./src/ip/alu/rtl/ialu.sv ]
read_verilog [ glob ./src/ip/alu/rtl/falu.sv ]
read_verilog [ glob ./src/ip/branch/rtl/** ]
read_verilog [ glob ./src/ip/decoder/params/** ]
read_verilog [ glob ./src/ip/decoder/rtl/** ]
read_verilog [ glob ./src/ip/jump/rtl/** ]
read_verilog [ glob ./src/ip/lsu/rtl/** ]
read_verilog [ glob ./src/ip/mem/params/** ]
read_verilog [ glob ./src/ip/mem/rtl/** ]
read_verilog [ glob ./src/ip/pc/rtl/** ]
read_verilog [ glob ./src/ip/regs/rtl/** ]
read_verilog [ glob ./src/ip/sextend/rtl/** ]
read_xdc ./vivado/riscy.xdc