name: iverilog compile

on:
  push:
    branches:
      - main

jobs:
  set_enviroment:
    runs-on: ubuntu-latest
    steps:
      - name: SetUp SSH
        env:
          SSH_PRIVATE: ${{ secrets.ACTIONS_SSH_PRIVATE }}
          SSH_PUBLIC: ${{ secrets.ACTIONS_SSH_PUBLIC }}
          ARTIFACT_NAME: "RTL_build_$(TZ='America/New_York' date '+%F-%H')"
          OUT_PATH: ${{ env.PWD }}/out
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE }}" > ~/.ssh/id_rsa
          echo "${{ env.SSH_PUBLIC }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
      - name: Download required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog
      - name: Clone project repo
        run: |
          git clone --recurse-submodules git@github.com:Clarkson-RISC-V-2023/top-main.git
          mkdir -p out 
      - name: Build PC
        run: |
          iverilog -o out/pc_sim -s tb_pc top-main/src/ip/pc/verif/tb_pc.sv top-main/src/ip/pc/rtl/pc.sv
          cd out/
          vvp pc_sim
          cd ..
          tree
      - name: Build ROM
        run: |
          iverilog -o out/rom_sim -s tb_rom top-main/src/ip/rom/verif/tb_rom.sv top-main/src/ip/rom/rtl/rom.sv -y ./top-main/src/ip/rom/
          cd out/
          vvp rom_sim
          cd ..
          tree
      - name: Upload Artifact 
        uses: actions/upload-artifact@v2
        with:
          name: "RTL_build"
          path: |
            **/out/**
          if-no-files-found: error
