name: iverilog compile

on: 
  push: 
    branches: 
      - main 
# git checkout ${{ steps.extract_branch.outputs.branch }}
jobs:
  set_enviroment:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      # git checkout ${{ steps.extract_branch.outputs.branch }}

      - name: Pull Docker image 
        run:
          docker pull ernessola/verilog_compiler:latest
      - name: Run Docker image 
        run: |
          docker run --name RISCy_compiler -i ernessola/verilog_compiler:latest bash -c "git fetch && git checkout ${{ steps.extract_branch.outputs.branch }} && git pull && make all" 
          docker cp RISCy_compiler:/workspace/top-main/out .
          docker stop RISCy_compiler
          docker rm RISCy_compiler
      - name: Upload Artifact 
        uses: actions/upload-artifact@v2
        with:
          name: "main_RTL_build"
          path: |
            **/out/**
          if-no-files-found: error