name: RTL PR Sanity Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  Clone_Repo:
    runs-on: vivado-2023
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Recursive pull 
        shell: bash
        run:  |
              rm -rf * 
              git clone git@github.com:Clarkson-RISC-V-2023/top-main.git 
              cd top-main
              git checkout ${{ steps.extract_branch.outputs.branch }}
              git submodule update --init
              tree

  # Build-SIM_alu_ip:
  #   runs-on: vivado-2023
  #   needs: Clone_Repo
  #   steps:
  #     - name: IALU_sanity_check
  #       shell: bash
  #       run:  |
  #             cd top-main 
  #             make ialu
  #     - name: MALU_sanity_check
  #       shell: bash
  #       run:  |
  #             cd top-main 
  #             make malu

  Build-SIM_mem_ip:
    runs-on: vivado-2023
    needs: Clone_Repo
    steps:
      - name: MEMBLOCK_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make bmem
      - name: ROM_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make rom
      - name: RAM_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make ram
      - name: UVM_RAM_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make uvm_ram

  Build-SIM_branch_ip:
    runs-on: vivado-2023
    needs: Clone_Repo
    steps:
      - name: MEMBLOCK_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make branch

  Build-SIM_jump_ip:
    runs-on: vivado-2023
    needs: Clone_Repo
    steps:
      - name: MEMBLOCK_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make jump

  # Build-SIM_lsu_ip:
  #   runs-on: vivado-2023
  #   needs: Clone_Repo
  #   steps:
  #     - name: MEMBLOCK_sanity_check
  #       shell: bash
  #       run:  |
  #             cd top-main 
  #             make lsu

  Build-SIM_regs_ip:
    runs-on: vivado-2023
    needs: Clone_Repo
    steps:
      - name: MEMBLOCK_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make regs

  Build-SIM_pc_ip:
    runs-on: vivado-2023
    needs: Clone_Repo
    steps:
      - name: MEMBLOCK_sanity_check
        shell: bash
        run:  |
              cd top-main 
              make pc

  Upload_Sim_Artifact:
    runs-on: vivado-2023
    needs: [Build-SIM_mem_ip, Build-SIM_branch_ip, Build-SIM_jump_ip, Build-SIM_regs_ip, Build-SIM_pc_ip] #Build-SIM_alu_ip Build-SIM_lsu_ip,
    steps:
      - name: Upload Artifact 
        uses: actions/upload-artifact@v2
        with:
              name: "PR_RTL_build"
              path: |
                ./top-main/out/**
              if-no-files-found: error
      - name: Clean
        shell: bash
        run: rm -rf top-main

